### ISSUE TITLE
error in SSR build after page refresh 

### ISSUE THREAD

**Issue by anujsharma-bbd** [ivylaboratory/angular-carousel#103]
`TypeError: Cannot read property 'destroy' of undefined
    at CarouselComponent.ngOnDestroy (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:5767:22)
    at executeOnDestroys (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:184473:28)
    at cleanUpView (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:184397:9)
    at destroyViewTree (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:184223:21)
    at destroyLView (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:184375:9)
    at RootViewRef.destroy (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:184989:9)
    at E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:203733:52
    at Array.forEach (<anonymous>)
    at ApplicationRef.ngOnDestroy (E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:203733:29)
    at E:\2-3-upgrade\js-storefront\project\dist\project-server\main.js:186353:55`

I think only we need to add a safe operator in ngOnChanges() like "this.touches?.destroy();"

please resolve this issue asap

will be very thankful

**Comment by fl0wo** [comment]
For the Angular Universal (Pre-Rendering) Folks:

I've found a workaround for this:

Wrap the component with an ngIf:

`      <div *ngIf="hasDom">
               <carousel ...
               /carousel>
       </div>
`

And set the "hasDom" variable to true as follows:

` 
       hasDom: boolean = false;
      
        constructor() { }
      
        ngOnInit(): void {
          // @ts-
          AppComponent.isBrowser.subscribe(isBrowser => {
            this.hasDom = isBrowser;
          })
        }
`
  
  // AppComponent:
  
  `

              export class AppComponent implements OnInit{
                      static isBrowser = new BehaviorSubject<boolean>(false);
                    
                      constructor(
                        @Inject(PLATFORM_ID) private platformId: any) {
                        AppComponent.isBrowser.next(isPlatformBrowser(platformId));

`

**Comment by anujsharma-bbd** [comment]
thanks @fl0wo
